version: '3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    ports:
      - "54322:5432"
    container_name: psql-devclone